<?php
@session_start();

require_once("database/configs.php");
require_once("includes/system.php");
require_once("includes/utils.php");
require_once("layout-header.php");
require_once("includes/get-medicines.php");

// global reference to PDO object
$pdo = constant('pdo');

// Find the the last created checkup ID on checkups table
// Generate a unique form number with a combination of 
// Date today, and add +1 onto the last id, then pad with 
// 4 leading zeros. ex: Y-m-d-0000id
$checkupFormNumber = Helpers::generateFormNumber($pdo);
?>

<body>

    <!-- BEGIN CONTAINER -->
    <div class="container-fluid h-100 bg-document p-0">

        <!-- TITLE BANNER -->
        <?php include("layouts/banner.php") ?>
        <!-- TITLE BANNER -->

        <!-- MAIN CONTENT -->
        <main class="main-content-wrapper d-flex h-100 pt-5">

            <section class="d-flex flex-grow-1 mt-2 overflow-hidden">

                <!-- NAVIGATION -->
                <?php include("layouts/navigation.php") ?>

                <!--WORKAREA-->
                <section class="workarea w-100 pb-5">

                    <!--WELCOME BANNER-->
                    <?php include("layouts/welcome-banner.php"); ?>

                    <!--THE CHECKUP FORM-->
                    <div class="checkup-form-wrapper p-4 w-100 h-100 overflow-hidden position-relative">

                        <div class="checkup-form bg-white shadow-2-strong w-100 h-100 p-4 scrollable" style="overflow-y: auto;">

                            <div class="breadcrumb w-100 d-flex flex-row align-items-center justify-content-start">
                                <h6 class="fas fa-laptop font-teal"></h6>
                                <h6 class="ms-2 fw-bold">Transaction</h6>
                                <h6 class="breadcrumb-arrow fas fa-play mx-3"></h6>
                                <h6 class="fas fa-heartbeat font-red"></h6>
                                <h6 class="ms-2 fw-bold">Checkup</h6>
                            </div>

                            <form method="POST" id="checkup-form">

                                <!-- AUTOGENERATED CHECKUP FORM NUMBER-->
                                <div class="row mb-4">
                                    <div class="col-3">
                                        <h6 class="fw-bold font-red">Checkup Form Number</h6>
                                        <div class="form-outline">
                                            <input type="text" name="input-form-number" class="form-control input-form-number bg-white" value="<?php echo $checkupFormNumber ?>" readonly data-mdb-toggle="tooltip" title="Automatically Generated" />
                                        </div>
                                    </div>
                                    <div class="col-3"></div>
                                    <div class="col text-start">
                                        <h6 class="fw-bold font-teal">Checkup Date & Time</h6>
                                        <div class="d-flex flex-row gap-2">

                                            <div class="form-outline">
                                                <input type="text" name="input-checkup-date" class="form-control input-checkup-date bg-white" value="<?php echo Dates::dateToday("m/d/Y") ?>" readonly required />
                                            </div>
                                            <div class="form-outline">
                                                <input type="time" name="input-checkup-time" class="input-checkup-time py-1" value="<?php echo Dates::dateToday("H:i") ?>" required />
                                            </div>
                                            <button type="button" class="btn btn-secondary fw-bold btn-date-time-now">Now</button>
                                        </div>
                                    </div>
                                </div>

                                <!--DIVIDER-->
                                <div class="divider-separator border border-1 border-bottom mb-3"></div>

                                <div class="row">
                                    <div class="col-3">
                                        <h6 class="fw-bold font-base">Patient Information</h6>
                                    </div>
                                    <div class="col-3"></div>
                                    <div class="col text-start">
                                        <h6 class="fw-bold font-base">Medical Information</h6>
                                    </div>
                                </div>

                                <!--CLIENT FIELDS-->
                                <div class="row mb-3">

                                    <!-- LEFT -->
                                    <div class="col-3">

                                        <!-- FIRSTNAME -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-fname" class="form-control input-fname" value="" required />
                                            <label class="form-label" for="input-fname">Firstname</label>
                                        </div>
                                        <!-- MIDDLENAME -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-mname" class="form-control input-mname" value="" required />
                                            <label class="form-label" for="input-mname">Middlename</label>
                                        </div>
                                        <!-- LASTNAME -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-lname" class="form-control input-lname" value="" required />
                                            <label class="form-label" for="input-lname">Lastname</label>
                                        </div>
                                        <div class="dropdown mb-3">
                                            <button class="btn btn-secondary bg-base text-white dropdown-toggle w-100" type="button" id="patient-dropdown-button" data-mdb-toggle="dropdown" aria-expanded="false">
                                                Patient Type
                                            </button>
                                            <ul class="dropdown-menu" aria-labelledby="patient-dropdown-button">
                                                <li onclick="setPatientType(1)"><span class="dropdown-item dropdown-item-custom-dark">Student</span></li>
                                                <li onclick="setPatientType(2)"><span class="dropdown-item dropdown-item-custom-dark">Faculty</span></li>
                                                <li onclick="setPatientType(3)"><span class="dropdown-item dropdown-item-custom-dark">Staff</span></li>
                                            </ul>
                                            <input type="hidden" name="input-patient-type" class="input-patient-type" value="" required>
                                        </div>
                                        <!-- ADDRESS -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-address" class="form-control input-address" value="" required />
                                            <label class="form-label" for="input-address">Address</label>
                                        </div>
                                        <!-- CONTACT# -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-contact" class="form-control input-contact" maxlength="13" value="" required />
                                            <label class="form-label" for="input-contact">Contact#</label>
                                        </div>
                                        <!-- PARENT / GUARDIAN NAME -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-parent-guardian" class="form-control input-parent-guardian" value="" required />
                                            <label class="form-label" for="input-parent-guardian">Parent / Guardian</label>
                                        </div>
                                    </div>

                                    <!-- MIDDLE -->
                                    <div class="col-3">

                                        <!--BIRTHDAY-->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-birthday" class="form-control input-birthday bg-white" value="" readonly required />
                                            <label class="form-label" for="input-birthday">Birthday</label>
                                        </div>
                                        <div class="dropdown mb-3">
                                            <button class="btn btn-outline-secondary fw-bold text-dark dropdown-toggle w-100" type="button" id="gender-dropdown-button" data-mdb-toggle="dropdown" aria-expanded="false">
                                                Select Gender
                                            </button>
                                            <ul class="dropdown-menu" aria-labelledby="gender-dropdown-button">
                                                <li onclick="setGender('Male')"><span class="dropdown-item dropdown-item-custom-dark">Male</span></li>
                                                <li onclick="setGender('Female')"><span class="dropdown-item dropdown-item-custom-dark">Female</span></li>
                                            </ul>
                                            <input type="hidden" name="input-gender" class="input-gender" value="" required>
                                        </div>
                                        <!-- AGE AND WEIGHT -->
                                        <div class="d-flex align-items-center mb-2">
                                            <div class="form-outline mb-3 me-auto">
                                                <input type="text" name="input-age" class="form-control input-age" maxlength="3" required />
                                                <label class="form-label" for="input-age">Age</label>
                                            </div>
                                            <div class="form-outline mb-3 ms-2">
                                                <input type="text" name="input-weight" class="form-control input-weight" maxlength="6" required />
                                                <label class="form-label" for="input-weight">Weight (Kg)</label>
                                            </div>
                                        </div>
                                        <!--BLOOD PRESSURE-->
                                        <div class="blood-pressure-wrapper mb-4">
                                            <h6 class="mb-3">Blood Pressure</h6>
                                        </div>
                                        <div class="d-flex align-items-center mb-2">
                                            <div class="form-outline mb-3 me-auto">
                                                <input type="text" name="input-systolic" class="form-control input-systolic" maxlength="3" />
                                                <label class="form-label" for="input-systolic">Systolic</label>
                                            </div>
                                            <div class="form-outline mb-3 ms-2">
                                                <input type="text" name="input-diastolic" class="form-control input-diastolic" maxlength="3" />
                                                <label class="form-label" for="input-diastolic">Diastolic</label>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- RIGHT -->
                                    <div class="col">

                                        <div class="mb-3 row">
                                            <div class="col text-start">
                                                <div class="form-outline mb-3 ms-2">
                                                    <input type="text" name="input-illness" class="form-control input-illness bg-white" readonly data-mdb-toggle="modal" data-mdb-target="#illnessSelectorModal" />
                                                    <label class="form-label" for="input-illness">Illness / Disease</label>
                                                </div>
                                                <input type="hidden" name="input-illness-id" class="input-illness-id">
                                            </div>
                                            <div class="col-4 text-end">
                                                <button type="button" class="btn btn-secondary btn-clear-illness fw-bold">Clear</button>
                                            </div>
                                        </div>

                                        <h6 class="text-muted font-base">Prescription</h6>

                                        <div class="w-100 border border-1 border-secondary mb-2" style="height: 240px; overflow-y: auto;">

                                            <table class="table table-sm table-hover">
                                                <thead class="bg-amber text-dark">
                                                    <tr>
                                                        <th class="fw-bold" scope="col">Product Name</th>
                                                        <th class="fw-bold" scope="col">Category</th>
                                                        <th class="fw-bold" scope="col">Qty</th> 
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td scope="row">Biogesic</td>
                                                        <td>Paracetamol</td>
                                                        <td>1</td> 
                                                    </tr>
                                                    <tr>
                                                        <td scope="row">Neozep</td>
                                                        <td>Paracetamol</td>
                                                        <td>2</td> 
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="table-buttons d-flex flex-row-reverse gap-2">
                                            <button type="button" class="btn btn-secondary fw-bold" data-mdb-toggle="modal" data-mdb-target="#medicineSelectorModal">Add Medicine</button>
                                            <button type="button" class="btn btn-secondary fw-bold btn-clear-prescriptions">Clear All</button>
                                        </div>
                                    </div>
                                </div>

                                <!-- REMINDER -->
                                <div class="alert alert-warning text-center mb-3 d-flex flex-row flex-wrap align-items-center justify-content-center">
                                    <i class="fas fa-exclamation-triangle me-2"></i>
                                    <span>Please fill out all fields with accurate and valid information. Double check your entries before submitting.</span>
                                </div>

                                <!-- CONFIRMATION -->
                                <div class="d-flex align-items-center justify-content-center mb-4">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" value="" id="chk-confirm" />
                                        <label class="form-check-label" for="chk-confirm">I certify that all information provided above are accurate and complete</label>
                                    </div>
                                </div>

                                <!-- CONTROL BUTTONS -->
                                <div class="d-flex flex-row-reverse gap-2">
                                    <button type="button" class="btn btn-primary bg-base btn-submit" disabled>SUBMIT</button>
                                    <button type="button" class="btn btn-secondary fw-bold btn-reset">RESET</button>
                                </div>
                            </form>
                        </div>

                    </div>

                </section>

            </section>
        </main>
        <!-- MAIN CONTENT -->

    </div>
    <!-- END CONTAINER -->

    <!--SNACKBAR AND MODAL-->
    <?php
    include("components/alert-dialog/alert-dialog.php");
    include("components/snackbar/snackbar.php");
    ?>

    <!-- ILLNESS SELECTOR -->
    <div class="modal fade" id="illnessSelectorModal" tabindex="-1" aria-labelledby="illnessSelectorModalLabel" aria-hidden="true" data-mdb-backdrop="static">
        <div class="modal-dialog pt-3">
            <div class="modal-content mt-5">
                <div class="modal-header bg-base text-white py-0 ps-4 pe-0">
                    <h6 class="modal-title" id="illnessSelectorModalLabel">Select Illness</h6>
                    <button type="button" class="btn shadow-0 fs-5 text-white" data-mdb-dismiss="modal">
                        <i class="fas fa-times-circle"></i>
                    </button>
                </div>

                <div class="modal-body px-4">

                    <div class="select-box mb-3">
                        <select name="illness-starts-with" id="illness-starts-with">
                            <option selected value="all">Show All</option>
                            <option disabled value="">Begins With :</option>

                        </select>
                    </div>

                    <div class="w-100 border border-1 border-secondary mb-2 illness-selector-table-wrapper">

                        <table class="table table-sm table-striped table-hover">
                            <thead class="bg-amber text-dark">
                                <tr>
                                    <th scope="col" class="fw-bold">Medical Illness / Disease</th>
                                    <th scope="col" class="fw-bold">Action</th>
                                </tr>
                            </thead>
                            <tbody class="illness-selector-dataset">

                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="modal-footer py-2">
                    <button type="button" class="btn btn-secondary text-dark fw-bold" data-mdb-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!-- MEDICINES SELECTOR -->
    <div class="modal fade" id="medicineSelectorModal" tabindex="-1" aria-labelledby="medicineSelectorModalLabel" aria-hidden="true" data-mdb-backdrop="static">
        <div class="modal-dialog modal-lg pt-2">
            <div class="modal-content">
                <div class="modal-header bg-teal text-white py-0 ps-4 pe-0">
                    <h6 class="modal-title" id="medicineSelectorModalLabel">Select Medicine</h6>
                    <button type="button" class="btn shadow-0 fs-5 text-white" data-mdb-dismiss="modal">
                        <i class="fas fa-times-circle"></i>
                    </button>
                </div>

                <div class="modal-body px-4">

                    <div id="medicinePickerCarousel" class="carousel slide" data-mdb-ride="carousel"  data-mdb-interval="false">
                        <div class="carousel-inner">
                            <div class="carousel-item carousel-page-1  active">

                                <div class="select-box mb-2 d-flex flex-row align-items-center">
                                    <select name="filter-medicine-category" id="filter-medicine-category">
                                        <option selected value="all">Show All</option>
                                        <option value="only-selected">Only Selected</option>
                                        <option disabled value="">CATEGORIES :</option>
                                        <?php
                                        if (!empty($medicineCategories)) 
                                        {
                                            foreach ($medicineCategories as $c) 
                                            {
                                                echo "<option value='$c'>$c</option>";
                                            }
                                        }
                                        ?>
                                    </select>
                                    <div class="d-flex align-items-center flex-row gap-2 px-3">
                                        <div class="badge badge-secondary">Low on stock: </div>
                                        <div class="badge badge-warning me-4"><?php echo $criticalItemsCount; ?></div>
                                        <div class="badge badge-secondary">Sold Out: </div>
                                        <div class="badge badge-danger"><?php echo $soldOutItemsCount; ?></div>
                                    </div>
                                </div> 
                                <div class="w-100 border border-1 border-secondary mb-2 illness-selector-table-wrapper mb-2" style="height: 320px;">

                                    <table class="table table-sm table-striped table-hover medicines-table position-relative">
                                        <thead class="bg-base text-white position-sticky top-0">
                                            <tr class=""> 
                                                <th scope="col">Item Name</th>
                                                <th class="d-nonex">Category</th>
                                                <th scope="col">Stock</th> 
                                                <th scope="col">Action</th>
                                                <th class="d-none">IsSelected</th>
                                                <th class="d-none">ItemId</th>
                                                <th class="d-none">Remaining</th>
                                            </tr>
                                        </thead>
                                        <tbody class="medicine-selector-dataset">
                                            <?php
                                            if (!empty($medicineDataSet)) 
                                            {
                                                foreach ($medicineDataSet as $row) 
                                                { 
                                                    $id = $row['item_id'];
                                                    $item = $row['item_name'];
                                                    $category = $row['category'];
                                                    
                                                    $remaining = $row['remaining'];
                                                    $criticalLevel = $row['critical_level'];
                                                    
                                                    $stock = "<span class=\"badge badge-success\">Available</span>";
                                                    $btn_disableOnSoldOut = ($remaining == 0) ? "disabled" : "";

                                                    if ($remaining <= $criticalLevel)
                                                        $stock = "<span class=\"badge badge-warning\">Low on stock</span>";
                                                    
                                                    if ($remaining == 0)
                                                        $stock = "<span class=\"badge badge-danger\">Sold out</span>";

                                                    echo "
                                                <tr class=\"align-middle\"> 
                                                    <td>$item</td> 
                                                    <td class=\"d-nonex\">$category</td>
                                                    <td>$stock</td>
                                                    <td>
                                                        <button class=\"btn btn-primary btn-select-medicine bg-teal text-white py-1 px-0 text-center\" style=\"max-width: 92px; width: 92px;\" $btn_disableOnSoldOut>
                                                            Select
                                                        </button>
                                                    </td>
                                                    <td class=\"d-none\">false</td>
                                                    <td class=\"d-none\">$id</td>
                                                    <td class=\"d-none\">$remaining</td>
                                                </tr>";
                                                }
                                            } 
                                            ?>
                                        </tbody>
                                    </table>
                                </div> 
                            </div>
                            <div class="carousel-item carousel-page-2 ">
                                <img src="temp/camera.png" class="d-block w-100" alt="Camera" />
                            </div> 
                        </div>
                    </div>
                </div>

                <div class="modal-footer py-2">
                    <!-- <button type="button" class="btn btn-secondary text-dark fw-bold" data-mdb-dismiss="modal">Close</button> -->
                    <button class="btn btn-primary btn-carsl-back display-none" type="button" data-mdb-target="#medicinePickerCarousel" data-mdb-slide="prev">
                        BACK
                    </button>
                    <button class="btn btn-primary btn-carsl-next bg-base" type="button" data-mdb-target="#medicinePickerCarousel" data-mdb-slide="next">
                        NEXT
                    </button>
                    <button class="btn btn-primary btn-carsl-ok bg-base display-none" type="button" data-mdb-dismiss="modal">
                        OK
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!--SCRIPTS-->
    <script src="assets/lib/jquery/jquery-3.6.1.min.js"></script>
    <script src="assets/lib/jquery-ui-1.13.2.custom/jquery-ui.min.js"></script>
    <script src="assets/lib/mdb5/js/mdb.min.js"></script>
    <script src="assets/lib/momentjs/moment-with-locales.js"></script>
    <script src="assets/lib/jquery.nicescroll/jquery.nicescroll.min.js"></script>

    <script src="assets/js/nicescroll.js"></script>
    <script src="assets/js/system.js"></script>
    <script src="assets/js/checkup-form.js"></script>
    <script src="assets/js/welcome-banner.js"></script>

    <script src="components/alert-dialog/alert-dialog.js"></script>
    <script src="components/snackbar/snackbar.js"></script>
</body>

</html>