<?php
include("database/configs.php");
include("includes/system.php");
include("includes/helpers.php");
include("layout-header.php");

// Find the the last created checkup ID on checkups table
$lastCheckupFormId = Helpers::getLastId($pdo, TableNames::$checkup);

// Generate a unique form number with a combination of 
// Date today, and add +1 onto the last id, then pad with 
// 4 leading zeros. ex: Y-m-d-0000id
$checkupFormNumber = Dates::dateToday() . "-" . str_pad(($lastCheckupFormId + 1), 5, "0", STR_PAD_LEFT);
?>

<body>

    <!-- BEGIN CONTAINER -->
    <div class="container-fluid h-100 bg-document p-0">

        <!-- TITLE BANNER -->
        <?php include("layouts/banner.php") ?>
        <!-- TITLE BANNER -->

        <!-- MAIN CONTENT -->
        <main class="main-content-wrapper d-flex h-100 pt-5">

            <section class="d-flex flex-grow-1 mt-2 overflow-hidden">

                <!-- NAVIGATION -->
                <?php include("layouts/navigation.php") ?>

                <!--WORKAREA-->
                <section class="workarea w-100 pb-5">

                    <!--WELCOME BANNER-->
                    <div class="bg-secondary welcome-banner bg-control d-flex align-items-center px-4 fw-bold fs-6">
                        <span class="welcome-text me-auto">Welcome, user!</span>
                        <span class="date-banner"><?php echo Dates::dateToday("l, F d, Y"); ?></span>
                    </div>

                    <!--THE CHECKUP FORM-->
                    <div class="checkup-form-wrapper p-4 w-100 h-100 overflow-hidden position-relative">

                        <div class="checkup-form bg-white shadow-2-strong w-100 h-100 p-4 scrollable" style="overflow-y: auto;">
                            <form action="" method="POST">

                                <!-- AUTOGENERATED CHECKUP FORM NUMBER-->
                                <div class="row">
                                    <div class="col-3">
                                        <h6 class="fw-bold font-red">Checkup Form Number</h6>
                                        <div class="form-outline mb-4">
                                            <input type="email" name="" class="form-control input-auto-form-number" value="<?php echo $checkupFormNumber ?>" readonly />
                                        </div>
                                    </div>
                                    <div class="col">

                                    </div>
                                </div>

                                <h6 class="fw-bold font-base">Client Information</h6>

                                <!--CLIENT FIELDS-->
                                <div class="row">

                                    <!-- LEFT -->
                                    <div class="col-3">

                                        <!-- FIRSTNAME -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-fname" class="form-control" />
                                            <label class="form-label" for="input-fname">Firstname</label>
                                        </div>
                                        <!-- MIDDLENAME -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-mname" class="form-control" />
                                            <label class="form-label" for="input-fname">Middlename</label>
                                        </div>
                                        <!-- LASTNAME -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-lname" class="form-control" />
                                            <label class="form-label" for="input-lname">Lastname</label>
                                        </div>
                                        <!-- ADDRESS -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-address" class="form-control" />
                                            <label class="form-label" for="input-address">Address</label>
                                        </div>
                                        <!-- CONTACT# -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-contact" class="form-control" />
                                            <label class="form-label" for="input-contact">Contact#</label>
                                        </div>
                                        <!-- FATHERS NAME -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-father" class="form-control" />
                                            <label class="form-label" for="input-fathers-name">Father's Name</label>
                                        </div>
                                        <!-- MOTHERS NAME -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-mother" class="form-control" />
                                            <label class="form-label" for="input-mothers-name">Mother's Name</label>
                                        </div>
                                    </div>

                                    <!-- MIDDLE -->
                                    <div class="col-3">

                                        <!--BIRTHDAY-->
                                        <div class="d-flex align-items-center mb-3">
                                            <div class="me-auto">
                                                <h6 class="text-muted">Birthday</h6>
                                            </div>
                                            <div class="">
                                                <input type="date" name="" class="customized-date-picker">
                                            </div>
                                        </div>
                                        <!--AGE AND GENDER-->
                                        <div class="d-flex align-items-center">
                                            <div class="me-auto">
                                                <h6 class="text-muted">Gender</h6>
                                            </div>
                                            <div class="">
                                                <select name="" class="customized-combo-box">
                                                    <option disabled selected value="">Select Gender</option>
                                                    <option value="Male">Male</option>
                                                    <option value="Female">Female</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col"></div>
                                </div>
                            </form>
                        </div>

                    </div>

                </section>

            </section>
        </main>
        <!-- MAIN CONTENT -->

    </div>
    <!-- END CONTAINER -->


    <!--SCRIPTS-->
    <script src="lib/jquery/jquery-3.6.1.min.js"></script>
    <script src="lib/mdb5/js/mdb.min.js"></script>
    <script src="lib/jquery.nicescroll/jquery.nicescroll.min.js"></script>
    <script src="assets/js/nicescroll.js"></script>
</body>

</html>