<?php
@session_start();

require_once("database/configs.php");
require_once("includes/system.php");
require_once("includes/utils.php");
require_once("layout-header.php");

$pdo = constant('pdo');
// Find the the last created checkup ID on checkups table
$lastCheckupFormId = Helpers::getLastId($pdo, TableNames::$checkup);

// Generate a unique form number with a combination of 
// Date today, and add +1 onto the last id, then pad with 
// 4 leading zeros. ex: Y-m-d-0000id
$checkupFormNumber = Dates::dateToday() . "-" . str_pad(($lastCheckupFormId + 1), 5, "0", STR_PAD_LEFT);

?>

<body>

    <!-- BEGIN CONTAINER -->
    <div class="container-fluid h-100 bg-document p-0">

        <!-- TITLE BANNER -->
        <?php include("layouts/banner.php") ?>
        <!-- TITLE BANNER -->

        <!-- MAIN CONTENT -->
        <main class="main-content-wrapper d-flex h-100 pt-5">

            <section class="d-flex flex-grow-1 mt-2 overflow-hidden">

                <!-- NAVIGATION -->
                <?php include("layouts/navigation.php") ?>

                <!--WORKAREA-->
                <section class="workarea w-100 pb-5">

                    <!--WELCOME BANNER-->
                    <?php include("layouts/welcome-banner.php"); ?>

                    <!--THE CHECKUP FORM-->
                    <div class="checkup-form-wrapper p-4 w-100 h-100 overflow-hidden position-relative">

                        <div class="checkup-form bg-white shadow-2-strong w-100 h-100 p-4 scrollable" style="overflow-y: auto;">

                            <div class="breadcrumb w-100 d-flex flex-row align-items-center justify-content-start">
                                <h6 class="fas fa-laptop font-teal"></h6>
                                <h6 class="ms-2 fw-bold">Transaction</h6>
                                <h6 class="breadcrumb-arrow fas fa-play mx-3"></h6>
                                <h6 class="fas fa-heartbeat font-red"></h6>
                                <h6 class="ms-2 fw-bold">Checkup</h6>
                            </div>

                            <form method="POST" id="checkup-form">

                                <!-- AUTOGENERATED CHECKUP FORM NUMBER-->
                                <div class="row">
                                    <div class="col-3">
                                        <h6 class="fw-bold font-red">Checkup Form Number</h6>
                                        <div class="form-outline mb-4">
                                            <input type="text" name="input-form-number" class="form-control input-form-number bg-white" value="<?php echo $checkupFormNumber ?>" readonly data-mdb-toggle="tooltip" title="Automatically Generated" />
                                        </div>
                                    </div>
                                    <div class="col-3"></div>
                                    <div class="col text-start">
                                        <h6 class="fw-bold font-teal">Checkup Date & Time</h6>
                                        <div class="d-flex flex-row gap-2">
                                            <input type="date" name="input-checkup-date" class="input-checkup-date" value="<?php echo Dates::dateToday() ?>" />
                                            <input type="time" name="input-checkup-time" class="input-checkup-time" value="<?php echo Dates::dateToday("H:i") ?>" />
                                            <button type="button" class="btn btn-secondary fw-bold btn-date-time-now">Now</button>
                                        </div>
                                    </div>
                                </div>

                                <!--DIVIDER-->
                                <div class="divider-separator border border-1 border-bottom mb-3"></div>

                                <div class="row">
                                    <div class="col-3">
                                        <h6 class="fw-bold font-base">Client Information</h6>
                                    </div>
                                    <div class="col-3"></div>
                                    <div class="col text-start">
                                        <h6 class="fw-bold font-base">Medical Information</h6>
                                    </div>
                                </div>

                                <!--CLIENT FIELDS-->
                                <div class="row mb-3">

                                    <!-- LEFT -->
                                    <div class="col-3">

                                        <!-- FIRSTNAME -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-fname" class="form-control input-fname" value="" required />
                                            <label class="form-label" for="input-fname">Firstname</label>
                                        </div>
                                        <!-- MIDDLENAME -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-mname" class="form-control input-mname" value="" required />
                                            <label class="form-label" for="input-mname">Middlename</label>
                                        </div>
                                        <!-- LASTNAME -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-lname" class="form-control input-lname" value="" required />
                                            <label class="form-label" for="input-lname">Lastname</label>
                                        </div>
                                        <!-- ADDRESS -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-address" class="form-control input-address" value="" required />
                                            <label class="form-label" for="input-address">Address</label>
                                        </div>
                                        <!-- CONTACT# -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-contact" class="form-control input-contact" maxlength="13" value="" required />
                                            <label class="form-label" for="input-contact">Contact#</label>
                                        </div>
                                        <!-- FATHERS NAME -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-fathers-name" class="form-control input-fathers-name" value="" required />
                                            <label class="form-label" for="input-fathers-name">Father's Name</label>
                                        </div>
                                        <!-- MOTHERS NAME -->
                                        <div class="form-outline mb-3">
                                            <input type="text" name="input-mothers-name" class="form-control input-mothers-name" value="" required />
                                            <label class="form-label" for="input-mothers-name">Mother's Name</label>
                                        </div>
                                    </div>

                                    <!-- MIDDLE -->
                                    <div class="col-3">

                                        <!--BIRTHDAY-->
                                        <div class="d-flex align-items-center mb-3">
                                            <div class="me-auto">
                                                <h6 class="text-muted">Birthday</h6>
                                            </div>
                                            <div class="mb-2">
                                                <input type="date" name="input-bday" class="customized-date-picker input-bday" required>
                                            </div>
                                        </div>
                                        <!--AGE AND GENDER-->
                                        <div class="d-flex align-items-center mb-3">
                                            <div class="me-auto">
                                                <h6 class="text-muted">Gender</h6>
                                            </div>
                                            <div class="">
                                                <select name="input-gender" class="customized-combo-box input-gender" required>
                                                    <option disabled selected value="">Select Gender</option>
                                                    <option value="Male">Male</option>
                                                    <option value="Female">Female</option>
                                                </select>
                                            </div>
                                        </div>
                                        <!-- AGE AND WEIGHT -->
                                        <div class="d-flex align-items-center mb-2">
                                            <div class="form-outline mb-3 me-auto">
                                                <input type="text" name="input-age" class="form-control input-age" maxlength="3" required />
                                                <label class="form-label" for="input-age">Age</label>
                                            </div>
                                            <div class="form-outline mb-3 ms-2">
                                                <input type="text" name="input-weight" class="form-control input-weight" maxlength="6" required />
                                                <label class="form-label" for="input-weight">Weight (Kg)</label>
                                            </div>
                                        </div>
                                        <!--BLOOD PRESSURE-->
                                        <div class="blood-pressure-wrapper mb-4">
                                            <h6 class="mb-3">Blood Pressure</h6>
                                        </div>
                                        <div class="d-flex align-items-center mb-2">
                                            <div class="form-outline mb-3 me-auto">
                                                <input type="text" name="input-systolic" class="form-control input-systolic" maxlength="3" />
                                                <label class="form-label" for="input-systolic">Systolic</label>
                                            </div>
                                            <div class="form-outline mb-3 ms-2">
                                                <input type="text" name="input-diastolic" class="form-control input-diastolic" maxlength="3" />
                                                <label class="form-label" for="input-diastolic">Diastolic</label>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- RIGHT -->
                                    <div class="col">

                                        <div class="mb-3 row">
                                            <div class="col text-start">
                                                <div class="form-outline mb-3 ms-2">
                                                    <input type="text" name="textbox-illness" class="form-control input-illness bg-white" readonly />
                                                    <label class="form-label" for="input-illness">Illness</label>
                                                </div>
                                                <input type="hidden" name="input-illness-id" class="input-illness-id">
                                            </div>
                                            <div class="col-4 text-end">
                                                <button type="button" class="btn btn-secondary fw-bold">Select Illness</button>
                                            </div>
                                        </div>

                                        <h6 class="text-muted font-base">Prescription</h6>

                                        <div class="w-100 border border-1 border-secondary mb-2" style="height: 240px; overflow-y: auto;">

                                            <table class="table table-sm table-hover">
                                                <thead class="bg-amber text-dark">
                                                    <tr>
                                                        <th scope="col">Product Name</th>
                                                        <th scope="col">Category</th>
                                                        <th scope="col">Qty</th>
                                                        <th scope="col">Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <th scope="row">1</th>
                                                        <td>Mark</td>
                                                        <td>Otto</td>
                                                        <td>@mdo</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">2</th>
                                                        <td>Jacob</td>
                                                        <td>Thornton</td>
                                                        <td>@fat</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">3</th>
                                                        <td colspan="2">Larry the Bird</td>
                                                        <td>@twitter</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">1</th>
                                                        <td>Mark</td>
                                                        <td>Otto</td>
                                                        <td>@mdo</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">2</th>
                                                        <td>Jacob</td>
                                                        <td>Thornton</td>
                                                        <td>@fat</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">3</th>
                                                        <td colspan="2">Larry the Bird</td>
                                                        <td>@twitter</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="table-buttons d-flex flex-row-reverse gap-2">
                                            <button type="button" class="btn btn-secondary fw-bold">Add Medicine</button>
                                            <button type="button" class="btn btn-secondary fw-bold">Clear All</button>
                                        </div>
                                    </div>
                                </div>

                                <!-- REMINDER -->
                                <div class="alert alert-warning text-center mb-3 d-flex flex-row flex-wrap align-items-center justify-content-center">
                                    <i class="fas fa-exclamation-triangle me-2"></i>
                                    <span>Please fill out all fields with accurate and valid information. Double check your entries before submitting.</span>
                                </div>

                                <!-- CONFIRMATION -->
                                <div class="d-flex align-items-center justify-content-center mb-4">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" value="" id="chk-confirm" />
                                        <label class="form-check-label" for="chk-confirm">I certify that all information provided above are accurate and complete</label>
                                    </div>
                                </div>

                                <!-- CONTROL BUTTONS -->
                                <div class="d-flex flex-row-reverse gap-2">
                                    <button type="button" class="btn btn-primary bg-base btn-submit" disabled>SUBMIT</button>
                                    <button type="reset" class="btn btn-secondary fw-bold btn-reset">RESET</button>
                                </div>
                            </form>
                        </div>

                    </div>

                </section>

            </section>
        </main>
        <!-- MAIN CONTENT -->

    </div>
    <!-- END CONTAINER -->

    <!--SNACKBAR -->
    <?php
 
    // if ($checkupFormMsg != "")
    // {
    //     echo "<div class=\"snackbar w-100 snackbar-success py-2 px-4 position-fixed bottom-0 d-flex flex-row align-items-center\">$checkupFormMsg</div>";

    //     echo "<script>$(document).ready(() => {
    //         $('snackbar').fadeTo(1000, 0, function() {
    //             $(this).hide();
    //         });
    //     });</script>";
    // }

    ?>

    <!--SCRIPTS-->
    <script src="assets/lib/jquery/jquery-3.6.1.min.js"></script>
    <script src="assets/lib/mdb5/js/mdb.min.js"></script>
    <script src="assets/lib/momentjs/moment-with-locales.js"></script>
    <script src="assets/lib/jquery.nicescroll/jquery.nicescroll.min.js"></script>
    <script src="assets/js/nicescroll.js"></script>
    <script src="assets/js/system.js"></script>
    <script src="assets/js/checkup-form.js"></script>
    <script src="assets/js/welcome-banner.js"></script> 

</body>

</html>