<?php
require_once("rootcwd.php");
require_once($rootCwd . "controllers/CheckupFormController.php");
?>

<body>

    <?php $masterPage->beginWorkarea(Navigation::NavIndex_Checkup); //BEGIN WORKAREA LAYOUT 
    ?>

    <!-- BEGIN MAIN WORKAREA -->
    <div id="main-workarea" class="flex-grow-1 d-flex flex-column h-100 bg-white shadow-2-strong overflow-hidden py-2">

        <? // BREADCRUMB 
        ?>
        <div class="breadcrumbs px-4 w-100 d-flex flex-row align-items-center justify-content-start">
            <img src="assets/images/icons/sidenav-transaction.png" width="20" height="20">
            <div class="fs-6 fw-bold ms-2">Transaction</div>
            <div class="breadcrumb-arrow fsz-12 fas fa-play mx-3"></div>
            <img src="assets/images/icons/sidenav-checkup-form.png" width="20" height="20">
            <div class="ms-2 fw-bold fs-6">Checkup Form</div>
        </div>

        <hr class="hr divider" />

        <? // PATIENT INFORMATION SECTION 
        ?>
        <div data-simplebar class="flex-grow-1 checkup-form-fields h-100 overflow-y-auto no-native-scroll">

            <form action="<?= Tasks::CREATE_CHECKUP ?>" class="overflow-hidden mx-4 px-2" method="POST" id="checkup-form">

                <? // AUTOGENERATED CHECKUP FORM NUMBER 
                ?>
                <div class="row">
                    <div class="col-3">
                        <h6 class="font-indigo">Transaction Number</h6>
                        <div class="form-outline">
                            <input type="text" name="input-form-number" class="form-control input-form-number bg-white" value="<?= $checkupFormNumber ?>" readonly data-mdb-toggle="tooltip" title="Automatically Generated" />
                        </div>
                    </div>
                    <div class="col-3"></div>
                    <div class="col text-start">

                        <h6 class="font-teal">Checkup Date & Time</h6>

                        <div class="d-flex flex-row gap-2">
                            <div class="form-outline">
                                <input type="text" name="checkup-date" class="form-control input-checkup-date bg-white" value="<?= Dates::dateToday("m/d/Y") ?>" readonly />
                            </div>
                            <div class="form-outline me-auto h-36">
                                <input type="time" name="checkup-time" class="input-checkup-time py-1 px-2 font-form-control mdb-border-1" value="<?= Dates::dateToday("H:i") ?>" readonly />
                            </div>
                            <?php 
                                $previewKey = get_onCreatePreviewKey();

                                if (!empty($previewKey))
                                {
                                    echo <<<DIV
                                    <div class="preview-checkup">
                                        <button type="button" class="btn btn-secondary btn-preview py-1 px-2 h-36" data-mdb-toggle="tooltip" data-mdb-placement="left" title="Click to view the last created record">
                                            <div class="d-flex align-items-center gap-2">
                                                <span class="me-2">Preview</span>
                                                <img src="assets/images/icons/icn_preview-checkup.png" width="28" height="28">
                                            </div>
                                        </button>
                                    </div>
                                    DIV;
                                }
                            ?>
                        </div>
                    </div>
                </div>

                <hr class="hr divider" />

                <!-- FORM COLUMN SUBHEADINGS -->
                <div class="row mb-2">
                    <div class="col-3">
                        <h6 class="font-base">Patient Information</h6>
                    </div>
                    <div class="col-3"></div>
                    <div class="col-3">
                        <h6 class="font-base">Medical Information</h6>
                    </div>
                </div>

                <!-- ERROR MESSAGE WRAPPER -->
                <div class="row">
                    <div class="col">
                        <div class="bg-red-light p-2 rounded-2 mb-3 display-none error-message">
                            <i class="fas fa-exclamation-triangle font-red-dark me-1"></i>
                            <small class="font-red-dark error-label">Error Message</small>
                        </div>
                    </div>
                </div>

                <?php // HIDDEN VALUES FOR SENSITIVE DATA 
                ?>
                <input type="text" name="patient-key" class="d-none selected-patient-key" value="<?= $forwardPatientKey ?>">
                <input type="text" name="illness-id" class="d-none illness-id">
                <input type="text" name="doctor-key" class="d-none doctor-key" value="<?= $defaultPhysicianKey ?>">
                <input type="text" name="prescriptions" class="d-none prescriptions">

                <div class="row mb-3">
                    <div class="col-3">
                        <div class="form-outline">
                            <input type="text" class="form-control bg-white text-primary patient-idnum h-36" name="input-idnum" readonly required data-mdb-toggle="tooltip" data-mdb-placement="left" title='Click "Find" to open the list of registered patients' value="<?= loadPatientDetails('idNum') ?>" />
                            <label for="input-idnum" class="form-label">ID Number</label>
                        </div>
                    </div>
                    <div class="col-3">
                        <button type="button" class="btn btn-secondary fw-bold px-2 me-2 btn-find-patient" data-mdb-toggle="modal" data-mdb-target="#findPatientsModal">
                            <i class="fas fa-search"></i>
                            <span class="ms-1">Find</span>
                        </button>
                        <button type="button" class="btn btn-secondary fw-bold px-2 btn-new-patient" data-mdb-toggle="tooltip" data-mdb-placement="top" title="Click to register a new patient">
                            <i class="fas fa-plus"></i>
                            <span class="ms-1">New</span>
                        </button>
                    </div>
                    <div class="col-4">
                        <div class="form-outline" data-mdb-toggle="modal" data-mdb-target="#findIllnessModal">
                            <input type="text" name="input-illness" class="form-control input-illness text-primary bg-white h-36" readonly data-mdb-toggle="tooltip" data-mdb-placement="left" title="Click to show the list of Illnesses / Diseases">
                            <label class="form-label" for="input-illness">Illness / Disease *</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-3">
                        <div class="form-outline mb-3">
                            <input type="text" class="form-control bg-white text-primary patient-name h-36" readonly data-mdb-toggle="tooltip" data-mdb-placement="left" title='Click "Find" to open the list of registered patients' value="<?= loadPatientDetails('name') ?>" />
                            <label class="form-label" for="patient-name">Patient Name</label>
                        </div>
                        <div class="form-outline">
                            <input type="text" class="form-control bg-white text-primary physician h-36" value="<?= $defaultPhysicianName ?>" readonly data-mdb-toggle="modal" data-mdb-target="#findDoctorModal" />
                            <label class="form-label" for="physician">Physician</label>
                        </div>
                    </div>
                    <div class="col-3">
                        <div class="patient-type-lbl-wrapper display-none">
                            <div class="d-flex align-items-center gap-2 h-36">
                                <small>Patient Type:</small>
                                <h6 class="mb-0 patient-type-lbl font-primary-dark"></h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <!-- <div class="fs-6 fw-bold text-muted">Blood Pressure</div>
                        <small>(Required if illness is Hypertension / Anemia)</small> -->
                        <div class="mb-3 d-flex align-items-center h-36">
                            <h6 class="mb-0 font-base">Vitals Signs <small>(Optional)</small></h6>
                        </div>
                        <div class="input-group mb-3">
                            <span class="input-group-text h-36" id="basic-addon1">Blood Pressure</span>
                            <!-- <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" /> -->
                            <input type="text" class="form-control input-systolic numeric h-36" placeholder="Systolic" name="bp-systolic">
                            <input type="text" class="form-control input-diastolic numeric h-36" placeholder="Diastolic" name="bp-diastolic">
                        </div>
                    </div>
                </div>

                <!-- PAST MEDICAL HISTORY -->
                <div class="past-medical-history display-none">
                    <hr class="hr">
                    <div class="row mb-2">
                        <div class="col">
                            <h6 class="font-base">Past Medical History</h6>
                        </div>
                        <div class="col text-end">
                            <button type="button" class="btn btn-secondary btn-expand btn-sm display-none" style="width: 124px; min-width: 124px; max-width: 124px;">
                                <span>Show More</span>
                                <i class="fas fa-chevron-down expand-arrow ms-1"></i>
                            </button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="table-wrapper border" style="overflow-y: auto; max-height: 255px;">
                                <table class="table table-sm table-borderless table-striped">
                                    <thead class="position-sticky top-0 z-10" style="background-color: #F1F3F5;">
                                        <tr>
                                            <th class="font-base" scope="col">Past Illness</th>
                                            <th class="font-base" scope="col">Physician</th>
                                            <th class="font-base" scope="col">Checkup Date</th>
                                            <th class="font-base" scope="col">Time</th>
                                        </tr>
                                    </thead>
                                    <tbody class="history-body">

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                <hr class="hr my-4 divider" />

                <!-- PRESCRIPTION HEADINGS  -->
                <div class="row mb-2">
                    <div class="col-6 d-flex align-items-center">
                        <h6 class="font-base">Medical Prescription</h6>
                    </div>
                    <div class="col text-end">
                        <button type="button" class="btn btn-primary bg-teal btn-sm btn-add-medicine me-2" data-mdb-toggle="modal" data-mdb-target="#selectMedicineModal">
                            <i class="fas fa-plus"></i>
                            <span class="ms-1">Add Medicine</span>
                        </button>
                        <button type="button" class="btn btn-secondary btn-clear-prescription fw-bold py-1 px-2 me-2 display-none">
                            <i class="fas fa-undo"></i>
                            <span class="ms-1">Clear</span>
                        </button>
                    </div>
                </div>
                <hr class="hr">
                <!-- PRESCRIPTION TABLE   -->
                <div class="prescription-wrapper display-none">
                    <div class="row">
                        <div class="col">
                            <div class="table-wrapper mb-2 border" style="overflow-y: auto; max-height: 310px;">
                                <table class="table table-sm table-borderless table-striped table-hover prescription-table">
                                    <thead class="style-secondary position-sticky top-0 z-10">
                                        <tr>
                                            <th class="fw-bold" scope="col" style="max-width: 200px; width: 200px;">Medicine</th>
                                            <th class="fw-bold" scope="col" style="max-width: 200px; width: 200px;">Stock</th>
                                            <th class="fw-bold" scope="col" style="max-width: 200px; width: 200px;">Available</th>
                                            <th class="fw-bold text-center" scope="col" style="max-width: 200px; width: 200px;">Quantity</th>
                                            <th class="fw-bold text-center" scope="col" style="max-width: 140px; width: 140px;">Action</th>
                                            <th class="d-none" scope="col">ItemKey</th>
                                            <th class="d-none" scope="col">Stock Data</th>
                                            <th class="d-none" scope="col">Units Label</th>
                                        </tr>
                                    </thead>
                                    <tbody class="prescription-body"></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="control-buttons d-flex align-items-center flex-row justify-content-end gap-2">
                    <button type="button" class="btn btn-secondary fw-bold btn-reset">Reset</button>
                    <button type="button" class="btn btn-primary btn-base btn-submit">Submit</button>
                </div>
            </form>
            <form action="<?= Pages::CHECKUP_DETAILS ?>" method="post" class="d-none frm-preview-checkup">
                <input type="text" name="record-key" value="<?= $previewKey ?>" />
            </form>
        </div>

    </div>
    <!-- END MAIN WORKAREA -->

    <?php $masterPage->endWorkarea(); //END WORKAREA LAYOUT 
    ?>

    <?php // SERVER MESSAGES SAVED ONTO SESSION 
    ?>
    <form class="d-none">
        <input type="text" class="checkup-success-message" value="<?= getSuccessMessage() ?>">
        <input type="text" class="registration-route" value="<?= $registrationGoBackRoute ?>">
        <input type="text" class="checkup-error" value="<?= $checkupErrorMsg ?>">
        <input type="text" class="forward-appointment-key" value="<?= $forwardPatientKey ?>">
    </form>

    <d class="d-none">
        <input type="text" class="medical-history-url" value="<?= AsyncActions::GET_MEDICAL_HISTORY ?>" />
    </d>

    <!--SNACKBAR AND MODAL-->
    <?php

    $masterPage->includeDialogs(true, true, true, true);

    require_once($rootCwd . "includes/embed.medicine-picker.php");
    require_once($rootCwd . "includes/embed.physician-picker.php");
    require_once($rootCwd . "includes/embed.illness-picker.php");
    require_once($rootCwd . "includes/embed.patient-picker.php");

    ?>


    <!--SCRIPTS-->
    <script src="assets/lib/jquery/jquery-3.6.1.min.js"></script>
    <script src="assets/lib/jquery-ui-1.13.2.custom/jquery-ui.min.js"></script>
    <script src="assets/lib/datatables/datatables.min.js"></script>
    <script src="assets/lib/mdb5/js/mdb.min.js"></script>
    <script src="assets/lib/mdb5/js/mdb.form-validation.js"></script>
    <script src="assets/lib/momentjs/moment-with-locales.js"></script>
    <script src="assets/lib/jquery.nicescroll/jquery.nicescroll.min.js"></script>
    <script src="assets/lib/simplebar/simplebar.min.js"></script>

    <script src="assets/js/nicescroll.js"></script>
    <script src="assets/js/system.js"></script>
    <script src="assets/js/base-ui.js"></script>
    <script src="assets/js/page.transaction-checkup-form.js"></script>

    <script src="components/confirm-dialog/confirm-dialog.js"></script>
    <script src="components/alert-dialog/alert-dialog.js"></script>
    <script src="components/snackbar/snackbar.js"></script>
    <script src="components/toast/toast.js"></script>
</body>

</html>